import { useState } from "react";
import AdminLayout from "@/components/admin/AdminLayout";
import { useInternationalProducts } from "@/hooks/use-international";
import { loadShopSettings, saveShopSettingsAndWait, type ShopSettings } from "@/lib/store";
import ReadyPaletteAdmin from "@/pages/admin/ReadyPaletteAdmin";

export default function CommerceCollections({ section }: { section: "palettes" | "mail-club" | "animation-merch" }) {
  const [settings, setSettings] = useState<ShopSettings>(() => loadShopSettings());
  const [saving, setSaving] = useState(false); const international = useInternationalProducts();
  const save = async () => { setSaving(true); try { await saveShopSettingsAndWait(settings); } finally { setSaving(false); } };
  const title = section === "palettes" ? "Palettes" : section === "mail-club" ? "Mail Club" : "Animation Merch";
  return <AdminLayout title={title} actions={<button className="button-primary" onClick={save} disabled={saving}>{saving ? "Saving…" : "Save changes"}</button>}>
    {section === "palettes" && <div className="space-y-8"><section className="admin-card"><h2 className="font-serif text-2xl">Custom Palette</h2><label className="mt-4 flex gap-3"><input type="checkbox" checked={settings.paletteSettings.enabled} onChange={(e) => setSettings({ ...settings, paletteSettings: { ...settings.paletteSettings, enabled: e.target.checked } })}/>Enabled</label><label className="mt-4 block">Price (TRY minor units)<input type="number" className="mt-1 block border p-2" value={settings.paletteSettings.priceMinor} onChange={(e) => setSettings({ ...settings, paletteSettings: { ...settings.paletteSettings, priceMinor: Number(e.target.value) } })}/></label><p className="mt-3 text-sm">Shipping: Free · Türkiye only</p></section><ReadyPaletteAdmin settings={settings} onChange={setSettings}/></div>}
    {section === "mail-club" && <section className="admin-card"><h2 className="font-serif text-2xl">Editions</h2><p className="mt-2 text-sm">Only one current edition is shown on the homepage.</p>{settings.mailClubEditions.map((edition, index) => <div className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-5" key={edition.id}><input aria-label="Edition title" className="border p-2" value={edition.title} onChange={(e) => { const list=[...settings.mailClubEditions]; list[index]={...edition,title:e.target.value}; setSettings({...settings,mailClubEditions:list}); }}/><input aria-label="Price" type="number" className="border p-2" value={edition.priceMinor} onChange={(e) => { const list=[...settings.mailClubEditions]; list[index]={...edition,priceMinor:Number(e.target.value)}; setSettings({...settings,mailClubEditions:list}); }}/><input aria-label="Stock" type="number" className="border p-2" value={edition.stock} onChange={(e) => { const list=[...settings.mailClubEditions]; list[index]={...edition,stock:Number(e.target.value)}; setSettings({...settings,mailClubEditions:list}); }}/><label className="flex items-center gap-2"><input type="checkbox" checked={edition.enabled} onChange={(e) => { const list=[...settings.mailClubEditions]; list[index]={...edition,enabled:e.target.checked}; setSettings({...settings,mailClubEditions:list}); }}/>Enabled</label><label className="flex items-center gap-2"><input type="radio" name="current-edition" checked={edition.current} onChange={() => setSettings({...settings,mailClubEditions:settings.mailClubEditions.map((item) => ({...item,current:item.id===edition.id}))})}/>Current</label></div>)}</section>}
    {section === "animation-merch" && <section className="admin-card"><h2 className="font-serif text-2xl">Synced Fourthwall products</h2><p className="mt-2 text-sm">Select products to show on the homepage. Checkout remains on Fourthwall.</p>{international.products.map((product) => <label className="mt-4 flex items-center gap-4 border-t pt-4" key={product.id}><input type="checkbox" checked={settings.animationMerchProductIds.includes(product.id)} onChange={(e) => setSettings({...settings,animationMerchProductIds:e.target.checked ? [...settings.animationMerchProductIds, product.id] : settings.animationMerchProductIds.filter((id) => id !== product.id)})}/>{product.primaryImage && <img className="h-16 w-16 object-contain" src={product.primaryImage.url} alt=""/>}<span><strong>{product.name}</strong><br/><small>{product.price.formatted} · {product.available ? "Available" : "Unavailable"}</small></span></label>)}</section>}
  </AdminLayout>;
}
